config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    get "/search" => "searches#search", as: "search"
    get "/genre_search/:id" => "searches#genre_search", as: "genre_search"

    resources :items, only: [:index, :show]

    get "/customers/my_page" => "customers#show", as: "customer"
    get "/customers/information/edit" => "customers#edit", as: "edit_customer"
    patch "/customers/information" => "customers#update", as: "update_customer"
    get "/customers/unsubscribe" => "customers#unsubscribe", as: "unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw", as: "withdraw"

    delete "/cart_items/destroy_all" => "cart_items#destroy_all", as: "destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]

    #showの優先度を下げるために下に表記
    post "/orders/confirm" => "orders#confirm", as: "confirm"
    get "/orders/thanks" => "orders#thanks", as: "thanks"
    resources :orders, only: [:new, :create, :index, :show]

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end


  namespace :admin do
    get "" => "homes#top", as: "top"

    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :customers, only: [:index, :show, :edit, :update]

    resources :orders, only: [:show, :update]

    patch "/order_details/:id" => "order_details#update", as: "order_detail"
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :cart_items
  has_many :addresses

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { message: "カタカナを入力してください", with: /\A[ァ-ヶー－]+\z/ }
  validates :first_name_kana, presence: true, format: { message: "カタカナを入力してください", with: /\A[ァ-ヶー－]+\z/ }
  validates :postal_code, presence: true, format: {message: "ハイフンは入力しないでください", with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :tellphone_number, presence: true, format: {message: "ハイフンは入力しないでください", with: /\A\d{10,11}\z/ }
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+.)+[a-z]{2,})\z/i }
  validates :is_active, inclusion: { in: [true, false] }

  def address_display
    "〒" + postal_code + " " + address + " " + last_name + " " + first_name
  end
  
  # def active_for_authentication?
  #   super && (invalid == true)
  # end
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:success] = "会員情報が更新されました。"
      redirect_to admin_customer_path(@customer)
    else
      render "edit"
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana,
    :first_name_kana, :postal_code, :address, :tellphone_number, :email, :is_active)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <div class="container">
      <div class="row">
        <div class="offset-1">
          <div style="color: red; font-weight: bold;">
            <%= render 'layouts/errors', obj: @customer %>
          </div>
          <br>
          <h4 class="customer-index-title", style="background-color: #ECECEC;">
             <%= @customer.last_name %> <%=@customer.first_name %>さんの会員情報編集
          </h4>
          <br>
        </div>

        <div class = "col-sm-10 px-sm-0 mx-auto">
          <%= form_with model:@customer, url: admin_customer_path(@customer), local:true do |f| %>
          <table class="table-spacing-edit">
            <tr>
              <td class="col-4"><strong>会員ID</strong></td>
              <td><%= @customer.id %></td>
            </tr>
            <tr>
              <td class="col-4"><strong>氏名</strong></td>
              <td>
                <div>
                  <%= f.text_field :last_name, class: "form-control last_name" %>
                </div>
              </td>
              <td>
                <div>
                  <%= f.text_field :first_name, class: "form-control last_name" %>
                </div>
              </td>
            </tr>
            <tr>
              <td class="col-4"><strong>フリガナ</strong></td>
              <td>
                <div>
                  <%= f.text_field :last_name_kana, class: "form-control last_name_kana" %>
                </div>
              </td>
              <td>
                <div>
                  <%= f.text_field :first_name_kana, class: "form-control last_name_kana" %>
                </div>
              </td>
            </tr>
            <tr>
              <td class="col-4"><strong>郵便番号</strong></td>
              <td>
                <div>
                  <%= f.text_field :postal_code, class: "form-control postal_code" %>
                </div>
              </td>
            </tr>
            <tr>
              <td class="col-4"><strong>住所</strong></td>
              <td>
                <div>
                  <%= f.text_field :address, class: "form-control address" %>
                </div>
              </td>
            </tr>
            <tr>
              <td class="col-4"><strong>電話番号</strong></td>
              <td>
                <div>
                  <%= f.text_field :tellphone_number, class: "form-control tellphone_numbe" %>
                </div>
              </td>
            </tr>
            <tr>
              <td class="col-4"><strong>メールアドレス</strong></td>
              <td>
                <div>
                  <%= f.text_field :email, class: "form-control email" %>
                </div>
              </td>
            </tr>
            <tr>
              <td class="col-4"><strong>会員ステータス</strong></td>
              <td>
                <div class="field">
                  <%= f.radio_button :is_active, 'true' %> 有効
                  <%= f.radio_button :is_active, 'false' %> 退会
                </div>
              </td>
            </tr>
            <tr class="table-spacing-edit-button">
              <td colspan="1"></td>
              <td>
                <div class="form-group">
                  <%= f.submit "変更を保存", class: "btn btn-lg btn-success" %>
                </div>
              </td>
            </tr>
          </table>
          <% end %>
        </div>
      </div>
    </div>


</html>

app/views/admin/customers/index.html.erb
  <div class="container">
    <div class="row">
      <div class="offset-1">
        <br>
        <h4 class="customer-index-title", style="background-color: #ECECEC;">　会員一覧　</h4>
      </div>
      
      <div class = "col-10 px-sm-0 mx-auto">
        <table class="table">
          <thead>
            <tr>
              <th class="table-active">会員ID</th>
              <th class="table-active">氏名</th>
              <th class="table-active">メールアドレス</th>
              <th class="table-active">ステータス</th>
            </tr>
          </thead>

          <tbody>
            <% @customers.each do |customer| %>
              <tr>
                <td><%= customer.id %></td>
                <td>
                  <%= link_to admin_customer_path(customer) do %>
                  <%= customer.last_name %><%= customer.first_name %>
                  <% end %>
                </td>
                <td><%= customer.email %></td>
                <td>
                  <% if customer.is_active %>
                    <strong class="text-success">有効</strong>
                  <% else %>
                    <strong class="text-secondary">退会</strong>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>


  <div class="pagination d-flex justify-content-center">
    <%= paginate @customers %>
  </div>

app/views/admin/customers/show.html.erb
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <div class="container">
    <div class="row">
      <div class="offset-1">
        <div style="color: #32cd32; font-weight: bold;">
          <%= flash[:success] %>
        </div>
        <div>
          <br>
          <h4 class="customer-index-title", style="background-color: #ECECEC;">
            <%= @customer.last_name %> <%=@customer.first_name %>さんの会員詳細
          </h4>
        </div>
      </div>

      <div class = "col-sm-10 px-sm-0 mx-auto">
        <table class="table-spacing-show">
          <tr>
            <td><strong>会員ID</strong></td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td><strong>氏名</strong></td>
            <td><%= @customer.last_name %>  <%= @customer.first_name %></td>
          </tr>

          <tr>
            <td><strong>フリガナ</strong></td>
            <td><%= @customer.last_name_kana %>  <%= @customer.first_name_kana %></td>
          </tr>
          <tr>
            <td><strong>郵便番号</strong></td>
            <td><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <td><strong>住所</strong></td>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <td><strong>電話番号</strong></td>
            <td><%= @customer.tellphone_number %></td>
          </tr>
          <tr>
            <td><strong>メールアドレス</strong></td>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <td><strong>会員ステータス</strong></td>
            <td>
              <% if @customer.is_active %>
                <strong class="text-success">有効</strong>
              <% else %>
                <strong class="text-secondary">退会</strong>
              <% end %>
            </td>
          </tr>
          <tr>
            <td colspan="1"></td>
            <td>
              <%= link_to '編集', edit_admin_customer_path(@customer), class: "btn btn-success" %>
            </td>
            <td>
              <%= link_to '注文履歴一覧を見る', admin_top_path, class: "btn btn-primary" %>
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>


</html>