config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    get "/search" => "searches#search", as: "search"
    get "/genre_search/:id" => "searches#genre_search", as: "genre_search"

    resources :items, only: [:index, :show]

    get "/customers/my_page" => "customers#show", as: "customer"
    get "/customers/information/edit" => "customers#edit", as: "edit_customer"
    patch "/customers/information" => "customers#update", as: "update_customer"
    get "/customers/unsubscribe" => "customers#unsubscribe", as: "unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw", as: "withdraw"

    delete "/cart_items/destroy_all" => "cart_items#destroy_all", as: "destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]

    #showの優先度を下げるために下に表記
    post "/orders/confirm" => "orders#confirm", as: "confirm"
    get "/orders/thanks" => "orders#thanks", as: "thanks"
    resources :orders, only: [:new, :create, :index, :show]

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end


  namespace :admin do
    get "" => "homes#top", as: "top"

    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :customers, only: [:index, :show, :edit, :update]

    resources :orders, only: [:show, :update]

    patch "/order_details/:id" => "order_details#update", as: "order_detail"
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: {waiting: 0, paied: 1, making: 2, ready_to_ship: 3, shipped: 4}

  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :name, presence: true

  def address_display
    "〒" + postal_code + " " + address + " " + name
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @customer = Customer.find(params[:customer_id])
    @orders = @customer.orders
  end 

  def show
    @order = Order.find(params[:id])
    @orders = Order.all
    @order_details = OrderDetail.where(order_id: @order.id)
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: @order.id)
    if @order.update(status_params)
      if @order.status == "paied"

        @order_details.update( making_status: 1)
      end
    flash[:order] = "注文ステータスを変更しました。"
    redirect_to admin_order_path(@order)
    else
      render "show"
    end
  end


  private

  def status_params
    params.require(:order).permit(:status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-auto">
      <h4 class="px-4" style="background-color:#ECECEC;">注文履歴詳細</h4>
    </div>
  </div>

  <table>
    <tbody>
    <tr>
      <th class="p-2">購入者</th>
      <td class="p-2">
        <%= link_to admin_customer_path(@order.customer) do %>
         <%= @order.customer.last_name + @order.customer.first_name %>
        <% end %>
      </td>
    </tr>

    <tr>
      <th class="p-2">注文日</th>
      <td class="p-2">
        <%= @order.created_at.strftime("%Y/%m/%d") %>
      </td>
    </tr>

    <tr>
      <th class="p-2">配送先</th>
      <td class="p-2">
        〒<%= @order.postal_code.to_s.insert(3, "-") %>
          <%= @order.address %>
          <%= @order.name %>
      </td>
    </tr>

    <tr>
      <th class="p-2">支払方法</th>
      <td class="p-2">
        <%= @order.payment_method_i18n %>
      </td>
    </tr>

    <tr>
      <th class="p-2">注文ステータス</th>
      <td class="p-2">
       <%= form_with model: @order, url: admin_order_path, method: :patch, local: true do |f| %>
         <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
         <%= f.submit "更新", class: "btn btn-sm btn-success offset-1" %>
       <% end %>
      </td>
      <td class = "text-success"><%= flash[:order] %></td>
    </tr>
    </tbody>
  </table>

  <div class="row align-items-end mt-4">
    <div class="col-lg-9 col-sm-auto">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th class="table-secondary text-center">商品名</th>
            <th class="table-secondary text-center">単価(税込)</th>
            <th class="table-secondary text-center">数量</th>
            <th class="table-secondary text-center">小計</th>
            <th class="table-secondary text-center">製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_detail| %>
          <tr>
            <td class = "text-center"><%= order_detail.item.name %></td>
            <td class = "text-center"><%= number_with_delimiter(order_detail.price) %></td>
            <td class = "text-center"><%= order_detail.amount %></td>
            <td class = "text-center"><%= number_with_delimiter(order_detail.subtotal) %>円</td>
            <td class = "text-center">
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), method: :patch, local: true do |f| %>
              <%= f.hidden_field :order_detail_id, :value => order_detail.id %>
              <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
              <%= f.submit "更新", class: "btn btn-sm btn-success offset-1" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <table class ="col-lg-3 col-sm-auto">
      <tr>
        <th class = "px-2"><strong>商品合計</strong></th>
        <td class = "px-2">
          <%=  number_with_delimiter(@order.total_payment - @order.shipping_cost) %>円
        </td>
      </tr>

      <tr class="border-bottom border-4 border-dark">
        <th class = "p-2"><strong>送料</strong></th>
        <td class = "p-2">
          <%=  number_with_delimiter(@order.shipping_cost) %>円
        </td>
      </tr>

      <tr>
        <th class = "py-3 px-2"><strong>請求金額合計</strong></th>
        <td class = "py-3 px-2">
          <strong><%=  number_with_delimiter(@order.total_payment) %>円</strong>
        </td>
      </tr>
    </table>
  </div>
</div>