config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    get "/search" => "searches#search", as: "search"
    get "/genre_search/:id" => "searches#genre_search", as: "genre_search"

    resources :items, only: [:index, :show]

    get "/customers/my_page" => "customers#show", as: "customer"
    get "/customers/information/edit" => "customers#edit", as: "edit_customer"
    patch "/customers/information" => "customers#update", as: "update_customer"
    get "/customers/unsubscribe" => "customers#unsubscribe", as: "unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw", as: "withdraw"

    delete "/cart_items/destroy_all" => "cart_items#destroy_all", as: "destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]

    #showの優先度を下げるために下に表記
    post "/orders/confirm" => "orders#confirm", as: "confirm"
    get "/orders/thanks" => "orders#thanks", as: "thanks"
    resources :orders, only: [:new, :create, :index, :show]

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end


  namespace :admin do
    get "" => "homes#top", as: "top"

    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :customers, only: [:index, :show, :edit, :update]

    resources :orders, only: [:show, :update]

    patch "/order_details/:id" => "order_details#update", as: "order_detail"
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer
  
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  
  def address_display
    "〒" + postal_code + " " + address + " " + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :cart_items
  has_many :addresses

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { message: "カタカナを入力してください", with: /\A[ァ-ヶー－]+\z/ }
  validates :first_name_kana, presence: true, format: { message: "カタカナを入力してください", with: /\A[ァ-ヶー－]+\z/ }
  validates :postal_code, presence: true, format: {message: "ハイフンは入力しないでください", with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :tellphone_number, presence: true, format: {message: "ハイフンは入力しないでください", with: /\A\d{10,11}\z/ }
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+.)+[a-z]{2,})\z/i }
  validates :is_active, inclusion: { in: [true, false] }

  def address_display
    "〒" + postal_code + " " + address + " " + last_name + " " + first_name
  end
  
  # def active_for_authentication?
  #   super && (invalid == true)
  # end
  
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items

  validates :name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :item_image

  has_many :cart_items  #"dependent: :destroy"の記載は商品の消去動作がないためつけていません
  has_many :order_details
  belongs_to :genre


  validates :name, presence: true, length: {maximum: 100}
  validates :description, presence: true, length: {maximum: 500}
  validates :genre_id, presence: true
  validates :price, presence: true, numericality:{ with: /\A[0-9]+\z/ }
  validates :is_active, inclusion: {in: [true, false]}

  def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      item_image.attach(io: File.open(file_path), filename: "no_image.jpg", content_type: "image/jpeg")
    end
    item_image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: {waiting: 0, paied: 1, making: 2, ready_to_ship: 3, shipped: 4}

  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :name, presence: true

  def address_display
    "〒" + postal_code + " " + address + " " + name
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :item
  belongs_to :order
  
  enum making_status: {not_statable: 0, waiting_for_pdoduction: 1, making: 2, finished: 3}

  def subtotal
    price * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:success] = "ジャンルの登録が完了しました"
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:success] = "ジャンルの編集が完了しました"
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  private
  #ストロングパラメータ
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @params = params[:id]
    @orders = Order.page(params[:page]).per(10).order(created_at: :desc)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = "商品が正常に登録されました。"
      redirect_to admin_item_path(@item.id)
    else
      @genres = Genre.all
      render 'new'
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "変更が正常に保存されました。"
      redirect_to admin_item_path(@item.id)
    else
      @genres = Genre.all
      render 'edit'
    end
  end

  private

  def item_params
    params.require(:item).permit(:item_image, :name, :description, :genre_id, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "件のエラー") %>が発生したため保存されませんでした。</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row" style="height:75px;">

  </div>
</div>

app/views/layouts/_header_admin.html.erb
<nav class="navbar navbar-expand-lg navbar-light justify-content-center">
  <div class="container">
    <a class="navbar-brand" href="/"><%= image_tag "Nagano_Cake_logo.jpg", size: "150x50" %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li class="nav-item">
            <%= link_to admin_items_path, class: "nav-link text-dark text-right" do %>
              <button class="btn btn-outline-dark">商品一覧</button>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_customers_path, class: "nav-link text-dark text-right" do %>
              <button class="btn btn-outline-dark">会員一覧</button>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_top_path, class: "nav-link text-dark text-right" do %>
              <button class="btn btn-outline-dark">注文履歴一覧</button>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_genres_path, class: "nav-link text-dark text-right" do %>
              <button class="btn btn-outline-dark">ジャンル一覧</button>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link text-dark text-right" do %>
              <button class="btn btn-outline-dark">ログアウト</button>
            <% end %>
        <% else %>
          <li class="nav-item">
            <%= link_to about_path, class: "nav-link text-dark text-right" do %>
              <button class="btn btn-outline-dark">About</button>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to items_path, class: "nav-link text-dark text-right" do %>
              <button class="btn btn-outline-dark">商品一覧</button>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_customer_registration_path, class: "nav-link text-dark text-right" do %>
              <button class="btn btn-outline-dark">新規登録</button>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_customer_session_path, class: "nav-link text-dark text-right" do %>
              <button class="btn btn-outline-dark">ログイン</button>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row d-flex">
    <div class="col-auto offset-3 text-secondary">
      <% if admin_signed_in? %>
        ※管理者ログイン中
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_header_public.html.erb
<nav class="navbar navbar-expand-lg navbar-light justify-content-center">
  <div class="container">
    <a class="navbar-brand" href="/"><%= image_tag "Nagano_Cake_logo.jpg", size: "150x50" %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <% if customer_signed_in? %>
          <li class="nav-item">
            <%= link_to customer_path, class: "nav-link text-dark text-right" do %>
              <button class="btn btn-outline-dark">マイページ</button>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to items_path, class: "nav-link text-dark text-right" do %>
              <button class="btn btn-outline-dark">商品一覧</button>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to cart_items_path, class: "nav-link text-dark text-right" do %>
              <button class="btn btn-outline-dark">カート</button>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_customer_session_path, method: :delete, class: "nav-link text-dark text-right" do %>
              <button class="btn btn-outline-dark">ログアウト</button>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to about_path, class: "nav-link text-dark text-right" do %>
              <button class="btn btn-outline-dark">About</button>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to items_path, class: "nav-link text-dark text-right" do %>
              <button class="btn btn-outline-dark">商品一覧</button>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_customer_registration_path, class: "nav-link text-dark text-right" do %>
              <button class="btn btn-outline-dark">新規登録</button>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_customer_session_path, class: "nav-link text-dark text-right" do %>
              <button class="btn btn-outline-dark">ログイン</button>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row d-flex">
    <div class="col-auto offset-4 text-dark">
      <% if customer_signed_in? %>
        ようこそ、<%= current_customer.last_name %>さん！
      <% end %>
    </div>
    <div class="col ml-auto flex-grow-0">
      <%= form_with url: search_path, local: true, method: :get, class: "d-flex h-75" do |f| %>
        <%= f.text_field :word, placeholder: "Search" %>
        <%= button_tag type: "submit", class: "btn btn-outline-secondary" do %>
          <i class="fa-solid fa-magnifying-glass align-top"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/8c365efc17.js" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="border-bottom">
      <% if admin_signed_in? %>
        <%= render 'layouts/header_admin' %>
      <% else %>
        <%= render 'layouts/header_public' %>
      <% end %>
    </header>
    <main class="mb-auto">
      <%= yield %>
    </main>
    <footer class="border-top">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>